### ISSUE TITLE
Support LuaJIT 2.0.5 for bytecode incompatibility reasons

### ISSUE THREAD

**Issue by brandonros** [khvzak/mlua#203]
Kind of a big ask so I 100% understand why you wouldn't want to do this

I forked https://github.com/brandonros/mlua and https://github.com/brandonros/luajit-src-rs and "patched" (hacked) this for myself.

I kind of rushed the "lua_resetthread" but that's all that it required so I figured maybe expand the `luajit` feature to something more customizable?

**Comment by khvzak** [comment]
You don't need to fork mlua if prefer to use your own `luajit-src` crate.
You can override the dependency to use your fork:

```toml
[patch.crates-io]
luajit-src = { git = "https://github.com/brandonros/luajit-src-rs" }
```
