### ISSUE TITLE
Is there a way to use the openssl library on luarocks?

### ISSUE THREAD

**Issue by JohnnnyWang** [khvzak/mlua#208]
For example, use [luaossl](https://luarocks.org/modules/daurnimator/luaossl) library to complete the functions of hmac.
I tried it, but running directly in ./luajit
```lua
-- ./luajit
local hmac = require "openssl.hmac"
-- and its ok
```
but in mlua, i got error like this:
Result::unwrap()` on an `Err` value: RuntimeError("error loading module '_openssl.hmac' from file '/usr/local/lib/lua/5.1/_openssl.so':\n\t/usr/local/lib/lua/5.1/_openssl.so: undefined symbol: lua_tolstring

Am I missing something? or is there any other way?
Thanks.

**Comment by khvzak** [comment]
https://github.com/khvzak/mlua/blob/master/FAQ.md#loading-a-c-module-fails-with-error-undefined-symbol-lua_xxx-how-to-fix

**Comment by khvzak** [comment]
I suppose the module `resty.hmac` is linked with dynamic symbols resolution and your application does not has openssl library loaded.
What you can do is link your app with openssl library (or use `rust-openssl` crate and [init](https://docs.rs/openssl/0.10.42/openssl/fn.init.html) it).

**Comment by JohnnnyWang** [comment]
Its works, Thank you

**Comment by liketoeatcheese** [comment]
Hi @khvzak,

I tried to follow this and add:
```toml
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-args=-rdynamic"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-args=-rdynamic"]
```

to `.cargo/config.toml`. But when I did `cargo run`, It didn't use it. But if I ran:
`export RUSTFLAGS="-C link-args=-rdynamic"; cargo run`

Then it works. Any thoughts on why? I also tried to add this but didn't work either:
```toml
[build]
target = "x86_64-unknown-linux-gnu"
```
