### ISSUE TITLE
new_with causes Lua 5.4 to panic

### ISSUE THREAD

**Issue by cbpudding** [khvzak/mlua#24]
I seem to have found an odd bug with `new_with` that causes mlua to panic. Attempting to disable part of the standard library causes the program to panic.

```Rust
use ::mlua::{Lua, StdLib};

fn main() {
	let state = Lua::new_with(StdLib::MATH);
}
```

```TOML
[package]
name = "mlua_test"
version = "0.1.0"
authors = ["Alexander Hill <CodeBreadpudding@gmail.com>"]
edition = "2018"

[dependencies]
mlua = { version = "0.4.2", features = ["lua54"] }
```

```
thread 'main' panicked at 'mlua internal error: Error during disabling C modules (this is a bug, please file an issue): FromLuaConversionError { from: "nil", to: "table", message: None }', /home/ahill/.cargo/registry/src/github.com-1ecc6299db9ec823/mlua-0.4.2/src/lua.rs:169:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

If there's anything I can do to help, let me know. Thanks in advance!

**Comment by khvzak** [comment]
Thanks for the bug report! I reproduced the bug and pushed a fix bd08aa1 to the dev branch. I'm preparing a new release and publish it in a few days with this fix.
The main reason was missing check for the `package` library presence before applying safety rules (to disable C modules).

**Comment by cbpudding** [comment]
I changed my Cargo.toml and it works! Thank you so much!

```TOML
[package]
name = "mlua_test"
version = "0.1.0"
authors = ["Alexander Hill <CodeBreadpudding@gmail.com>"]
edition = "2018"

[dependencies]
mlua = { git = "https://github.com/khvzak/mlua", branch = "dev", features = ["lua54"] }
```
