### ISSUE TITLE
./my_module.so: invalid ELF header

### ISSUE THREAD

**Issue by zackfall** [khvzak/mlua#248]
I'm trying to follow the example that is in the README for a lua module, but even if I just copy/paste the code and the configuration in the Cargo.toml, i get the same error once I try to run this command:
`lua5.4 -e 'require("my_module").hello("world")'`

This is all the output I get when run the code:
```
lua5.4: error loading module 'my_module' from file './my_module.so':
	./my_module.so: invalid ELF header
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	(command line):1: in main chunk
	[C]: in ?
```

I will place the code here, just in case is needed:
```rs
// src/lib.rs
use mlua::prelude::*;

fn hello(_: &Lua, name: String) -> LuaResult<()> {
    println!("hello, {name}!");
    Ok(())
}

#[mlua::lua_module]
fn my_module(lua: &Lua) -> LuaResult<LuaTable> {
    let exports = lua.create_table()?;
    exports.set("hello", lua.create_function(hello)?)?;
    Ok(exports)
}
```
```toml
# Cargo.toml
[package]
name = "my_module"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

crate-type = ["cdylib"]

[dependencies]
mlua = { version = "0.8", features = ["luajit", "vendored", "module"] }
```
And I'm a little confused about the output of the `cargo build --release` command, in the README says that it should create a file, in this case called `my_module.dylib` but when I go to the target folder, I just find a file named `my_module.rlib` I don't know if that happens because I'm in archlinux or something similar, but thats all the information I can offer, if someone could help me to understand how to use the crate properly would be great
