### ISSUE TITLE
Unable to require compiled modules in luau

### ISSUE THREAD

**Issue by CompeyDev** [khvzak/mlua#355]
# Environment
```yaml
Environment: Linux
Architecture: x86_64
Crate Version: 0.9.1
Features: luau, module
```
# Details

After compiling the example module example code on the README for luau, and then attempting to require it with in luau, it seems to fail with either of the following messages:

![case 1](https://github.com/khvzak/mlua/assets/74418041/daf966f1-b0b7-43a2-bb95-38b39dbae4d3)
![case 2](https://github.com/khvzak/mlua/assets/74418041/e4d72344-3b60-4c2a-8752-37363c7eb50e)

# Code

```rs
// lib.rs
use mlua::prelude::*;

fn hello(_: &Lua, name: String) -> LuaResult<()> {
    println!("hello, {}!", name);
    Ok(())
}

#[mlua::lua_module]
fn my_module(lua: &Lua) -> LuaResult<LuaTable> {
    let exports = lua.create_table()?;
    exports.set("hello", lua.create_function(hello)?)?;
    Ok(exports)
}
```
