### ISSUE TITLE
Integration tests fail with `dyld: Symbol not found: _luaopen_base` or `dyld: Symbol not found: _luaL_loadstring`

### ISSUE THREAD

**Issue by chipsenkbeil** [khvzak/mlua#79]
* Arch: Arm 64 ( Mac M1) 
* OS: Mac OS Big Sur
* Rust: 1.56.0
* Codebase: https://github.com/chipsenkbeil/distant/tree/AddLuaLib/distant-Lua 

I've got a workspace member of my repo that is configured as `cdylib` for the crate type. This is exposing a singular module and is able to be compiled via `cargo build` and `cargo build --release` without issue.

```toml
[package]
name = "distant-lua"
description = "Lua bindings to the distant Rust crates"
categories = ["api-bindings", "network-programming"]
keywords = ["api", "async"]
version = "0.15.0-alpha.6"
authors = ["Chip Senkbeil <chip@senkbeil.org>"]
edition = "2018"
homepage = "https://github.com/chipsenkbeil/distant"
repository = "https://github.com/chipsenkbeil/distant"
readme = "README.md"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
async-compat = "0.2.1"
distant-core = { version = "=0.15.0-alpha.6", path = "../distant-core" }
distant-ssh2 = { version = "=0.15.0-alpha.6", features = ["serde"], path = "../distant-ssh2" }
futures = "0.3.17"
mlua = { version = "0.6.4", features = ["luajit", "vendored", "module", "serialize", "async", "macros"] }
once_cell = "1.8.0"
oorandom = "11.1.3"
paste = "1.0.5"
serde = { version = "1.0.130", features = ["derive"] }
tokio = { version = "1.12.0", features = ["macros", "time"] }
whoami = "1.1.4"

[dev-dependencies]
rstest = "0.11.0"
```

Per the readme instructions, I added a `.cargo/config.toml` for my M1 macbook that contains

```toml
[target.x86_64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]

[target.aarch64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]
```

### Quick test

I wanted to begin writing tests to validate the logic of my Lua library, and wrote this dummy test first:

```rust
use mlua::{chunk, prelude::*};

#[test]
fn some_test() {
    let lua = Lua::new();

    let result = lua
        .load(chunk! {
            local x = 1+1
        })
        .exec();
    assert!(result.is_ok(), "Failed: {:?}", result);
}
```

The test fails to run, failing with `dyld: Symbol not found: _luaopen_base`.

### Trying link-args=-rdynamic

I then read through the test [`.cargo/config.toml`](https://github.com/khvzak/mlua/blob/master/tests/module/.cargo/config), which had `link-args=-rdynamic`, mentioned as needed for binaries in https://github.com/khvzak/mlua/issues/73. I'm assuming that this might be needed for the binary produced for integration tests, so changed my `.cargo/config.toml` to be

```toml
[target.x86_64-apple-darwin]
rustflags = ["-C", "link-args=-rdynamic"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-args=-rdynamic"]
```

Nothing changed with this from what I could see. I tried including it with the existing recommendation for building as well as on its own.

### Using make_lua

Reading through the module tests a bit, I noticed that it has a custom function to instantiate a Lua instance in the form of a function called [`make_lua`](https://github.com/khvzak/mlua/blob/master/tests/module/tests/load.rs#L71). I tried switching to that in my test.

After switching to that, I now get the error `dyld: Symbol not found: _luaL_loadstring`. So I'm at a loss as to what I should do to have a test run successfully.

```rust
use mlua::{chunk, prelude::*};

#[test]
fn some_test() {
    let lua = make_lua().unwrap();

    let result = lua
        .load(chunk! {
            local x = 1+1
        })
        .exec();
    assert!(result.is_ok(), "Failed: {:?}", result);
}

fn make_lua() -> Result<Lua> {
    let (dylib_path, dylib_ext, separator);
    if cfg!(target_os = "macos") {
        dylib_path = env::var("DYLD_FALLBACK_LIBRARY_PATH").unwrap();
        dylib_ext = "dylib";
        separator = ":";
    } else if cfg!(target_os = "linux") {
        dylib_path = env::var("LD_LIBRARY_PATH").unwrap();
        dylib_ext = "so";
        separator = ":";
    } else if cfg!(target_os = "windows") {
        dylib_path = env::var("PATH").unwrap();
        dylib_ext = "dll";
        separator = ";";
    } else {
        panic!("unknown target os");
    };

    let mut cpath = dylib_path
        .split(separator)
        .take(3)
        .map(|p| {
            let mut path = PathBuf::from(p);
            path.push(format!("lib?.{}", dylib_ext));
            path.to_str().unwrap().to_owned()
        })
        .collect::<Vec<_>>()
        .join(";");

    if cfg!(target_os = "windows") {
        cpath = cpath.replace("\\", "\\\\");
        cpath = cpath.replace("lib?.", "?.");
    }

    let lua = unsafe { Lua::unsafe_new() }; // To be able to load C modules
    lua.load(&format!("package.cpath = \"{}\"", cpath)).exec()?;
    Ok(lua)
}
```
