### ISSUE TITLE
[Question] Is there way to reload modules?

### ISSUE THREAD

**Issue by octaltree** [khvzak/mlua#84]
I can reload pure lua modules that have no side effects.
```lua
package.loaded['module name'] = nil
local m = require('module name')
```

I tried to do the same thing with mlua.
<details>
<summary>Cargo.toml</summary>

```toml
[package]
name = "reload"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
mlua = { version = "0.6.5", features = ["module", "luajit"] }

[features]
decrement = []
```
</details>

<details>
<summary>lib.rs</summary>

```rust
use mlua::prelude::*;

#[mlua::lua_module]
fn reload(lua: &Lua) -> LuaResult<LuaTable> {
    let exports = lua.create_table()?;
    exports.set("increment", lua.create_function(increment)?)?;
    #[cfg(feature = "decrement")]
    exports.set("decrement", lua.create_function(decrement)?)?;
    Ok(exports)
}

fn increment(_lua: &Lua, x: i32) -> LuaResult<i32> { Ok(x + 1) }

#[cfg(feature = "decrement")]
fn decrement(_lua: &Lua, x: i32) -> LuaResult<i32> { Ok(x - 1) }
```
</details>

run luajit in crate directory
```lua
os.execute("cargo build")
package.cpath = package.cpath .. ';./target/debug/lib?.so'
local reload = require('reload')
print(reload.increment(0))

os.execute("cargo build --features decrement")
package.loaded['reload'] = nil
reload = require('reload')
print(reload.decrement(1))
```
```
   Compiling reload v0.1.0 (/home/octaltree/workspace/reload)
    Finished dev [unoptimized + debuginfo] target(s) in 0.42s
1
   Compiling reload v0.1.0 (/home/octaltree/workspace/reload)
    Finished dev [unoptimized + debuginfo] target(s) in 0.41s
luajit: test.lua:9: attempt to call field 'decrement' (a nil value)
stack traceback:
        test.lua:9: in main chunk
        [C]: at 0x55a66cebbc20
```

Can you give me some advice?
